# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171106_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='notified',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.NotificationEvents'),
        ),
    ]
